default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

production:
  <<: *default
  database: my_database

development:
  <<: *default
  database: my_database_dev

test:
  <<: *default
  database: my_database_test

